version: '3'
services:
  db:
    build: "./db"
    volumes:
    - "./data:/var/lib/postgresql/data"
    environment:
    - POSTGRES_USER=jna
    - POSTGRES_PASSWORD=jna
    - POSTGRES_DB=jna
    restart: "always"
  api:
    build: "./api"
    ports:
    - "9000:9000"
    restart: "always"
    depends_on: 
      - db
  ui:
    build: "./ui"
    ports:
    - "8000:8000"
    restart: "always"
    environment:
    - VIRTUAL_HOST=jonathanadamski.com,www.jonathanadamski.com
    - VIRTUAL_PORT=8000
networks:
  default:
    external:
      name: ubuntu_default
