# Generated by Django 2.0.5 on 2018-06-02 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_deleted', models.CharField(default='', max_length=20, null=True)),
                ('name', models.CharField(max_length=40)),
                ('thumbnail_url', models.URLField(null=True)),
                ('code_url', models.URLField(null=True)),
                ('live_url', models.URLField(null=True)),
                ('skills', models.ManyToManyField(to='skills.Skill')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'date_deleted')},
        ),
    ]
